language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
install:
    - pip install -r test-requirements.txt --use-mirrors
    - python setup.py develop
script: nosetests
notifications:
    email: fabien.marty@gmail.com
    on_success: change
